const quotes = [
    //"\"Life is pleasant. Death is peaceful. It's the transition that's troublesome.\" - Isaac Asimov (1920-1992)",
    //"\"Be nice to people on your way up because you meet them on your way down.\" - Jimmy Durante (1893-1980)",
    //"\"If you want to make an apple pie from scratch, you must first create the universe.\" - Carl Sagan (1934-1996)",
    "\"Knowledge speaks, but wisdom listens.\" - Jimi Hendrix (1942-1970)",
    "\"Education is a progressive discovery of our own ignorance.\" - Will Durant (1885-1981)",
    "\"Obstacles are those frightful things you see when you take your eyes off your goal.\" - Henry Ford (1863-1947)",
    "\"While we are postponing, life speeds by.\" - Seneca (3BC-65AD)",
    //"\"First they ignore you, then they laugh at you, then they fight you, then you win.\" - Mahatma Gandhi (1869-1948)",
    "\"Most people would sooner die than think; in fact, they do so.\" - Bertrand Russell (1872-1970)",
    //"\"It has become appallingly obvious that our technology has exceeded our humanity.\" - Albert Einstein (1879-1955)",
    "\"The mistakes are all waiting to be made.\" - Chessmaster Savielly Grigorievitch Tartakower (1887-1956)",
    "\"Try not. Do, or do not. There is no 'try'.\" - Yoda",
    "\"I may not have gone where I intended to go, but I think I have ended up where I needed to be.\" - Douglas Adams (1952-2001)",
    //"\"Tell me, o Muse, of that ingenious hero who travelled far and wide...\" - Homer's Odyssey (800BC)",
    "\"Whatever trip we start, it is for the search of happiness. But happiness is here.\" - Quintus Flaccus (238-209)",
    "\"Nothing is constant but change.\" - Sakyamuni, founder of Buddhism (563-483)",
    "\"The only ones who fly are the ones who dare to fly.\" - Luis Sepulveda, Chilean writer (1949-)",
    "\"Stars are holes in the sky from which the light of the infinite shines.\" - Confucius (551-479)",
    //"\"While the other animals are prone and fix their gaze on the earth, the god gave man a face uplifted, bade him stand erect and turn his eyes to the stars.\" - Publius Ovidius Naso (Metamorphoses I. 84-6)",
    //"\"The greatest thing You'll ever learn Is just to love and Be loved in return\" - Eden Ahbez (1908-1995)",
    //"\"May god stand between you and harm, in all the dark places you must walk.\" - Ancient Egyptian Proverb",
    "\"To win one hundred victories in one hundred battles is not the highest skill. To subdue the enemy without fighting, is the highest skill.\" - Sun-Tsu (500BC)",
    "\"There must be something worth living for There must be something worth trying for Even some things worth dying for And if one man can stand tall There must be some hope for us all Somewhere, somewhere in the spirit of man\" - War of the Worlds musical by Jeff Wayne",
    //"\"Mother, I saw a dream in the night. There were stars in the sky for me.\" - The Epic of Gilgamesh (around 800 BC)",
    //"\"The greatest gain from space travel consists in the extension of our knowledge. In a hundred years this newly won knowledge will pay huge and unexpected dividends.\" - Wernher von Braun (1912-1977)",
    "\"To go places and do things that have never been done before - that's what living is all about.\" - Michael Collins (1930-)",
    "\"It's human nature to stretch, to go, to see, to understand. Exploration is not a choice, really; it's an imperative.\" - Michael Collins (1930-)",
    "\"Don't tell me that man doesn't belong out there. Man belongs wherever he wants to go - and he'll do plenty well when he gets there.\" - Wernher von Braun (1912-1977)",
    "\"Hold fast to dreams, for if dreams die, life is a broken bird that cannot fly.\" - Langston Hughes (1902-1967)",
    "\"Minds are like parachutes - they only function when open.\" - Thomas Dewar (1864-1930)",
    //"\"Shoot for the moon. Even if you miss, you'll land among the stars.\" - Les Brown (1945-)",
    "\"What is now proved was once only imagined.\" - William Blake (1757-1827)",
    "\"Even a fool knows you can't touch the stars, but it doesn't stop a wise man from trying.\" - Harry Anderson (1952-2018)",
    //"\"And if you gaze for long into an abyss, the abyss gazes also into you.\" - Friedrich Nietzsche (1844-1900)",
    //"\"Following the light of the sun, we left the Old World.\" - Inscription on Columbus' caravels",
    //"\"Throw your dreams into space like a kite, and you do not know what it will bring back, a new life, a new friend, a new love, a new country.\" - Anais Nin (1903-1977)",
    "\"If you can imagine it, you can achieve it. If you can dream it, you can become it.\" - William Arthur Ward (1921-1994)",
    "\"Imagination is the only weapon in the war against reality.\" - Jules de Gautier (1811-1872)",
    "\"The journey is the reward.\" - Taoist Saying",
    "\"It is good to have an end to journey toward, but it is the journey that matters in the end.\" - Ursula K. LeGuin (1929-2018)",
    "\"The universe is full of magical things patiently waiting for our wits to grow sharper.\" - Eden Phillpotts (1862-1960)",
    "\"Your current safe boundaries were once unknown frontiers.\" - Unknown",
    "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt (1884-1962)",
    "\"Dreams are renewable. No matter what our age or condition, there are still untapped possibilities within us and new beauty waiting to be born.\" - Dale Turner",
    "\"There is a single light of science, and to brighten it anywhere is to brighten it everywhere.\" - Isaac Asimov (1920-1992)",
    "\"Reality is that part of the imagination we all agree on.\" - Unknown",
    "\"The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.\" - Albert Einstein (1879-1955)",
    "\"Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.\" - Albert Einstein (1879-1955)",
    "\"When I examine myself and my methods of thought, I come to the conclusion that the gift of fantasy has meant more to me than my talent for absorbing positive knowledge.\" - Albert Einstein (1879-1955)",
    "\"As far as the laws of mathematics refer to reality, they are not certain; and as far as they are certain, they do not refer to reality.\" - Albert Einstein (1879-1955)",
    "\"Any sufficiently advanced technology is indistinguishable from magic.\" - Arthur C. Clarke (1917-2008)",
    //"\"Time is the fire in which we burn.\" - Delmore Schwartz (1913-1966)",
    //"\"I don't know what you could say about a day in which you have seen four beautiful sunsets.\" - John Glenn (1921-2016)",
    //"\"It suddenly struck me that that tiny pea, pretty and blue, was the Earth. I put up my thumb and shut one eye, and my thumb blotted out the planet Earth. I didn't feel like a giant. I felt very, very small.\" - Neil Armstrong (1930-2012)",
    "\"To confine our attention to terrestrial matters would be to limit the human spirit.\" - Stephen Hawking (1942-2018)",
    "\"Science-fiction yesterday, fact today, obsolete tomorrow.\" - Otto O. Binder (1911-1974)",
    "\"There shall be wings! If the accomplishment be not for me, 'tis for some other. The spirit cannot die; and man, who shall know all and shall have wings...\" - Leonardo da Vinci (1452-1519)",
    "\"Man's mind and spirit grow with the space in which they are allowed to operate.\" - Krafft A. Ehricke (1917-1984)",
    "\"The important thing is not to stop questioning.\" - Albert Einstein (1879-1955)",
    "\"You would make a ship sail against the winds and currents by lighting a bonfire under her deck...I have no time for such nonsense.\" - Napoleon Bonaparte (1769-1821)",
    "\"The Earth is a cradle of the mind, but we cannot live forever in a cradle.\" - Konstantin E. Tsiolkovsky (1857-1935)",
    //"\"Two possibilities exist: Either we are alone in the Universe or we are not. Both are equally terrifying.\" - Arthur C. Clarke (1917-2008)",
    "\"Space isn't remote at all. It's only an hour's drive away, if your car could go straight upwards.\" - Sir Fred Hoyle (1915-2001)",
    //"\"Space is big. Really big.\" - Douglas Adams (1952-2001)",
    //"\"I measured the skies Now the shadows I measure Skybound was the mind Earthbound the body rests.\" - Johannes Kepler (1571-1630)",
    "\"Discovery consists of seeing what everybody has seen and thinking what nobody has thought.\" - Albert Szent-Gyorgyi (1893-1986)",
    "\"Whether outwardly or inwardly, whether in space or time, the farther we penetrate the unknown, the vaster and more marvellous it becomes.\" - Charles A. Lindbergh (1902-1974)",
    "\"Scientists discover the world that exists; Engineers create the world that never was.\" — Theodore Von Karman (1881-1963)",
    "\"Scientific discovery and scientific knowledge have been achieved only by those who have gone in pursuit of it without any practical purpose whatsoever in view.\" — Max Planck (1858-1947)",
    "\"Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.\" — Archimedes (287-212 BC)",
    "\"When a distinguished but elderly scientist states that something is possible, he is almost certainly right. When he states that something is impossible, he is very probably wrong.\" — Arthur C. Clarke (1917-2008)",
    "\"Science may set limits to knowledge, but should not set limits to imagination.\" — Bertrand Russell (1872-1970)",
    "\"Nothing shocks me. I'm a scientist.\" — Indiana Jones",
    "\"Science is organized knowledge. Wisdom is organized life.\" — Immanuel Kant (1724-1804)",
    "\"A new scientific truth does not triumph by convincing its opponents and making them see the light, but rather because its opponents eventually die, and a new generation grows up that is familiar with it.\" — Max Planck (1858-1947)",
    "\"An investment in knowledge pays the best interest.\" — Benjamin Franklin (1706-1790)",
    "\"Anyone who has never made a mistake has never tried anything new.\" — Albert Einstein (1879-1955)",
    "\"Nature never breaks her own laws.\" — Leonardo da Vinci (1452-1519)",
    "\"Simplicity is the ultimate sophistication.\" — Leonardo da Vinci (1452-1519)",
    "\"Where there is shouting, there is no true knowledge.\" — Leonardo da Vinci (1452-1519)",
    "\"I have offended God and mankind because my work didn't reach the quality it should have.\" — Leonardo da Vinci (1452-1519)",
    "\"All our knowledge has its origins in our perceptions.\" — Leonardo da Vinci (1452-1519)",
    "\"By denying scientific principles, one may maintain any paradox.\" — Galileo Galilei (1564-1642)",
    "\"Mathematics is the language in which God has written the universe.\" — Galileo Galilei (1564-1642)",
    "\"If I were again beginning my studies, I would follow the advice of Plato and start with mathematics.\" — Galileo Galilei (1564-1642)",
    "\"We see only what we know.\" — Johann W. Goethe (1749-1832)",
    "\"If anybody says he can think about quantum problems without getting giddy, that only shows he has not understood the first thing about them.\" — Niels H. D. Bohr (1885-1962)",
    "\"Only one thing is certain - that is, nothing is certain. If this statement is true, it is also false.\" — Ancient paradox",
    "\"Scientists are explorers. Philosophers are tourists.\" — Richard Feynman (1918-1988)",
    "\"A great pleasure in life is doing what people say you cannot do.\" — Walter Bagehot (1826-1877)",
    "\"Genius is one percent inspiration and ninety-nine percent perspiration.\" — Thomas A. Edison (1847-1931)",
    "\"I know one thing: that I know nothing.\" — Socrates (470-399 BC)",
    "\"When you want to know how things really work, study them when they're coming apart.\" — William Gibson (1948-)",
    "\"Engineers like to solve problems. If there are no problems handily available, they will create their own problems.\" — Scott Adams (1957-)",
    "\"One man's 'magic' is another man's engineering. 'Supernatural' is a null word.\" — Robert A. Heinlein (1907-1988)",
    "\"A good scientist is a person with original ideas. A good engineer is a person who makes a design that works with as few original ideas as possible. There are no prima donnas in engineering.\" — Freeman Dyson (1923-2020)",
    "\"Aviation is the branch of engineering that is least forgiving of mistakes.\" — Freeman Dyson (1923-2020)",
    "\"To the optimist, the glass is half full. To the pessimist, the glass is half empty. To the engineer, the glass is twice as big as it needs to be.\" — Anonymous",
    "\"Scientists investigate that which already is; engineers create that which has never been.\" — Albert Einstein (1879-1955)",
    "\"Tracers work both ways.\" — U.S. Army Ordnance",
    "\"If you see a bomb technician running, follow him.\" — USAF Ammo Troop",
    "\"The only time you have too much fuel is when you're on fire.\" — Anonymous",
    "\"Never trade luck for skill.\" — Anonymous",
    "\"A pilot who doesn't have any fear probably isn't flying his plane to its maximum.\" — Jon McBride (1943-)",
    "\"To an engineer, good enough means perfect. With an artist, there's no such thing as perfect.\" — Alexander Calder (1898-1976)",
    "\"Mars is there, waiting to be reached.\" — Buzz Aldrin (1930-)",
    "\"This is one small step for a man, one giant leap for mankind.\" — Neil Armstrong (1930-2012)",
    "\"I see Earth! It is so beautiful!\" — Yuri Gagarin (1934-1968)",
    "\"I could have gone on flying through space forever.\" — Yuri Gagarin (1934-1968)",
    "\"To go places and do things that have never been done before - that's what living is all about.\" — Michael Collins (1930-2021)",
    "\"Do not go where the path may lead, go instead where there is no path and leave a trail.\" — Ralph W. Emerson (1803-1882)",
    "\"To be the first to enter the cosmos, to engage, single-handed, in an unprecedented duel with nature - could one dream of anything more?\" — Yuri Gagarin (1934-1968)",
    "\"The path of a cosmonaut is not an easy, triumphant march to glory. You have to get to know the meaning not just of joy but also of grief, before being allowed in the spacecraft cabin.\" — Yuri Gagarin (1934-1968)",
    "\"The dreams of yesterday are the hopes of today and the reality of tomorrow.\" — Robert H. Goddard (1882-1945)",
    "\"Failure is not an option.\" — Gene Kranz (1933-)",
    "\"No amount of experimentation can ever prove me right; a single experiment can prove me wrong.\" — Albert Einstein (1879-1955)",
    "\"Science never solves a problem without creating ten more.\" — George B. Shaw (1856-1950)",
    "\"The law of conservation of energy states that energy can be neither created nor destroyed. However, energy can change forms, and energy can flow from one place to another. The total energy of an isolated system remains the same.\" — The first law of thermodynamics",
    "\"The flow of heat is a form of energy transfer. In other words, a quantity of heat that flows from a hot body to a cold one can be expressed as an amount of energy being transferred from the hot body to the cold one.\" — The first law of thermodynamics",
    "\"Every body persists in its state of being at rest or of moving uniformly straight forward, except insofar as it is compelled to change its state by force impressed.\" — Newton's first law",
    "\"An object that is at rest will stay at rest unless an external force acts upon it.\" — Newton's first law",
    "\"An object that is in motion will not change its velocity unless an external force acts upon it.\" — Newton's first law",
    "\"The acceleration of a body is directly proportional to, and in the same direction as, the net force acting on the body, and inversely proportional to its mass.\" — Newton's second law",
    "\"To every action there is always an equal and opposite reaction: or the forces of two bodies on each other are always equal and are directed in opposite directions.\" — Newton's third law",
    "\"SCIENTIFIC METHOD: principles and procedures for the systematic pursuit of knowledge involving the recognition and formulation of a problem, the collection of data through observation and experiment, and the formulation and testing of hypotheses.\" — Wikipedia, 2077",
    "\"To be termed scientific, a method of inquiry must be based on empirical and measurable evidence subject to specific principles of reasoning.\" — Wikipedia, 2077",
    "\"The laws of science or scientific laws are statements that describe, predict, and perhaps explain why, a range of phenomena behave as they appear to in nature.\" — Wikipedia, 2077",
    "\"Scientific laws are strongly supported by empirical evidence - they are scientific knowledge that experiments have repeatedly verified (and never falsified).\" — Wikipedia, 2077",
    "\"Every point mass in the universe attracts every other point mass with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between them.\" — Newton's law of universal gravitation",
    "\"Creativity is intelligence having fun.\" — Albert Einstein (1879-1955)"
  ];

export function passQuotes() {
  let randomQuote = Math.floor(Math.random() * quotes.length);
  return quotes[randomQuote];
}